name = "your-lore"
main = "worker.js"
compatibility_date = "2025-06-16"

[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"
directory = "./dist"
run_worker_first = ["/*", "!/assets/*"]
